entryPoints:
  web:
    address: :9999
  tcp1:
    address: :9998
    
api:
  dashboard: true

log:
  level: DEBUG
#  filepath: logs

pilot:
    token: "add-your-own-traefik-pilot-token"
experimental:
    localPlugins:
    #plugins:
        sf:
            moduleName: "github.com/dariopb/traefikServiceFabricPlugin"
            #version: "v0.3.0"

providers:
  file:
    filename: "dyn.yaml"

  plugin:
    sf:
      pollInterval: 4s
      clusterManagementURL: http://localhost:19080
      #clusterManagementURL: http://darioclus1.southcentralus.cloudapp.azure.com:19080
      httpEntrypoint: web
      #certificate : ./cert.pem
      #certificateKey: ./cert.key
      #insecureSkipVerify: true